# Crear un resultado de laboratorio
POST http://localhost:3000/resultados-lab
Content-Type: application/json

{
  "imageurl": "http://example.com/image.png",
  "numeroDocumento": "12345678",
  "nombres": "John",
  "apePaterno": "Doe",
  "apeMaterno": "Smith",
  "fechaNacimiento": "1980-01-01T00:00:00Z",
  "numCelular": "123456789",
  "correoElectronico": "john.doe@example.com",
  "contrasena": "password",
  "repContrasena": "password",
  "genero": "M",
  "motivoPrueba": "Motivo de prueba",
  "fecha": "2024-06-22T00:00:00Z",
  "Resultado": "Resultado de prueba",
  "unidades": "mg/dL",
  "rangoNormal": "70-100",
  "ordenmedicaId": 1
}
