import { CrearResultadoLabDto } from "src/resultados-lab/dto/resultados-lab.dto"
export const defaultResultado: CrearResultadoLabDto[] = [
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]",
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
    {
        imageurl: "https://via.placeholder.com/150",
        numeroDocumento: "03264598",
        nombres: "Pedro",
        apePaterno: "Gonzales",
        apeMaterno: "Garcia",
        fechaNacimiento: new Date("12-06-1994"),
        numCelular: "943659456",
        correoElectronico: "asda@gmail.com",
        contrasena: "54454",
        repContrasena: "54454",
        genero: "Masculino",
        motivoPrueba: "Dolor de estomago",
        fecha: new Date("12-06-2024"),
        Resultado: "parasitos",
        unidades: "3",
        rangoNormal: "[1,2]"
    },
]